import React, { useState, useEffect } from 'react'
import styles from './App.module.css'
import Sidebar from './components/Sidebar'
import Chat from './components/Chat'
import type { GameState, ChatMessage } from './types'

function App() {
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [gameState, setGameState] = useState<GameState | null>(null)
  const [history, setHistory] = useState<ChatMessage[]>([])

  useEffect(() => {
    // Demo implementation. In a real environment, it polls or reads static JSON files generated by Cron.
    const fetchData = async () => {
      try {
        const stateRes = await fetch('/data/state.json')
        const stateData = await stateRes.json()
        setGameState(stateData)

        const historyRes = await fetch('/data/history.json')
        const historyData = await historyRes.json()
        setHistory(historyData)
      } catch (error) {
        console.error("Failed to load data", error)
      }
    }
    fetchData()
  }, [])

  if (!gameState) return <div style={{ padding: 40, fontFamily: 'var(--font-serif)' }}>Gathering the notes...</div>

  return (
    <div className={styles.appContainer}>
      <div className={`${styles.leftPanel} ${!sidebarOpen ? styles.collapsed : ''}`}>
        <Sidebar gameState={gameState} setGameState={setGameState} sidebarOpen={sidebarOpen} toggleSidebar={() => setSidebarOpen(!sidebarOpen)} />
      </div>
      
      <div className={styles.rightPanel}>
        <Chat 
          history={history} 
          gameState={gameState} 
        />
      </div>
    </div>
  )
}

export default App
